package com.swipeauctions.admin.enums;

/** One value per admin action that gets recorded to {@code AdminAuditLog}. */
public enum AuditAction {
    USER_SUSPENDED,
    USER_REACTIVATED,
    HOLD_RELEASED,
    AUCTION_FORCE_CLOSED,
    AUCTION_MODIFIED,
    LISTING_REQUIRED_TIER_CHANGED,
    LISTING_CATEGORY_CHANGED,
    DISPUTE_RESOLVED,
    CATEGORY_CREATED,
    CATEGORY_ATTRIBUTE_ADDED,
    KYC_APPROVED,
    KYC_REJECTED,
    STOCK_LISTING_CREATED,
    STOCK_BULK_IMPORTED,
    REGISTRATION_FEE_UPDATED,
    SUBSCRIPTION_PRICES_UPDATED,
    MEMBERSHIP_BENEFIT_ADDED,
    MEMBERSHIP_BENEFIT_TIERS_UPDATED,
    MEMBERSHIP_BENEFIT_REMOVED,
    ADMIN_CREATED,
    BANNER_CREATED,
    BANNER_REMOVED,
    REFERRAL_SETTINGS_UPDATED,
    BID_AMOUNT_MODIFIED,
    BIDDER_DISQUALIFIED,
    BIDDER_REINSTATED,
    WALLET_ADJUSTED
}
